// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sea_Trips_System;

#nullable disable

namespace Sea_Trips_System.Migrations
{
    [DbContext(typeof(SeaTripsContext))]
    [Migration("20260723061937_FixPropertyNamesToCamelCase")]
    partial class FixPropertyNamesToCamelCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sea_Trips_System.Models.Appointment", b =>
                {
                    b.Property<int>("appointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("appointmentId"));

                    b.Property<int>("boatId")
                        .HasColumnType("int");

                    b.Property<string>("bookingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<int>("destinationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("eventId")
                        .HasColumnType("int");

                    b.Property<int>("numberOfPeople")
                        .HasColumnType("int");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tripTypeId")
                        .HasColumnType("int");

                    b.HasKey("appointmentId");

                    b.HasIndex("boatId");

                    b.HasIndex("clientId");

                    b.HasIndex("destinationId");

                    b.HasIndex("eventId");

                    b.HasIndex("tripTypeId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.AppointmentStaff", b =>
                {
                    b.Property<int>("appointmentStaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("appointmentStaffId"));

                    b.Property<int>("appointmentId")
                        .HasColumnType("int");

                    b.Property<string>("assignedRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("staffId")
                        .HasColumnType("int");

                    b.HasKey("appointmentStaffId");

                    b.HasIndex("appointmentId");

                    b.HasIndex("staffId");

                    b.ToTable("AppointmentStaffs");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Boat", b =>
                {
                    b.Property<int>("boatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("boatId"));

                    b.Property<string>("boatName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<decimal>("hourlyRate")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("boatId");

                    b.HasIndex("boatName")
                        .IsUnique();

                    b.ToTable("Boat");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Client", b =>
                {
                    b.Property<int>("clientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clientId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("clientId");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Destination", b =>
                {
                    b.Property<int>("destinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("destinationId"));

                    b.Property<string>("coordinates")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("estimatedDuration")
                        .HasColumnType("time");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("destinationId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Event", b =>
                {
                    b.Property<int>("eventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eventId"));

                    b.Property<decimal>("discountRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("eventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("eventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Maintenance", b =>
                {
                    b.Property<int>("maintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maintenanceId"));

                    b.Property<int>("boatId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("maintenanceId");

                    b.HasIndex("boatId");

                    b.ToTable("Maintenance");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Payment", b =>
                {
                    b.Property<int>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentId"));

                    b.Property<decimal>("amountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("appointmentId")
                        .HasColumnType("int");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("transactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("paymentId");

                    b.HasIndex("appointmentId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Review", b =>
                {
                    b.Property<int>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reviewId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.HasKey("reviewId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Staff", b =>
                {
                    b.Property<int>("staffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("staffId"));

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("licenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("staffId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.TripType", b =>
                {
                    b.Property<int>("tripTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tripTypeId"));

                    b.Property<decimal>("basePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("typeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("tripTypeId");

                    b.ToTable("TripTypes");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Appointment", b =>
                {
                    b.HasOne("Sea_Trips_System.Models.Boat", "Boat")
                        .WithMany("Appointments")
                        .HasForeignKey("boatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sea_Trips_System.Models.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sea_Trips_System.Models.Destination", "Destination")
                        .WithMany("Appointments")
                        .HasForeignKey("destinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sea_Trips_System.Models.Event", "Event")
                        .WithMany("Appointments")
                        .HasForeignKey("eventId");

                    b.HasOne("Sea_Trips_System.Models.TripType", "TripType")
                        .WithMany("Appointments")
                        .HasForeignKey("tripTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boat");

                    b.Navigation("Client");

                    b.Navigation("Destination");

                    b.Navigation("Event");

                    b.Navigation("TripType");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.AppointmentStaff", b =>
                {
                    b.HasOne("Sea_Trips_System.Models.Appointment", "Appointment")
                        .WithMany("AppointmentStaffs")
                        .HasForeignKey("appointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sea_Trips_System.Models.Staff", "Staff")
                        .WithMany("AppointmentStaffs")
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Maintenance", b =>
                {
                    b.HasOne("Sea_Trips_System.Models.Boat", "Boat")
                        .WithMany("Maintenances")
                        .HasForeignKey("boatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boat");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Payment", b =>
                {
                    b.HasOne("Sea_Trips_System.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("appointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Review", b =>
                {
                    b.HasOne("Sea_Trips_System.Models.Appointment", "Appointment")
                        .WithMany("Reviews")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentStaffs");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Boat", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Client", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Destination", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Event", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.Staff", b =>
                {
                    b.Navigation("AppointmentStaffs");
                });

            modelBuilder.Entity("Sea_Trips_System.Models.TripType", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
